# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PING_CHECK.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PING_CHECK(object):
    def setupUi(self, PING_CHECK):
        PING_CHECK.setObjectName("PING_CHECK")
        PING_CHECK.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(PING_CHECK)
        self.centralwidget.setObjectName("centralwidget")
        self.IP_address = QtWidgets.QLineEdit(self.centralwidget)
        self.IP_address.setGeometry(QtCore.QRect(40, 50, 469, 25))
        self.IP_address.setObjectName("IP_address")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 469, 17))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 80, 471, 279))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PING = QtWidgets.QPushButton(self.widget)
        self.PING.setObjectName("PING")
        self.verticalLayout.addWidget(self.PING)
        self.output_window = QtWidgets.QTextEdit(self.widget)
        self.output_window.setObjectName("output_window")
        self.verticalLayout.addWidget(self.output_window)
        PING_CHECK.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PING_CHECK)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        PING_CHECK.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PING_CHECK)
        self.statusbar.setObjectName("statusbar")
        PING_CHECK.setStatusBar(self.statusbar)

        self.retranslateUi(PING_CHECK)
        QtCore.QMetaObject.connectSlotsByName(PING_CHECK)

    def retranslateUi(self, PING_CHECK):
        _translate = QtCore.QCoreApplication.translate
        PING_CHECK.setWindowTitle(_translate("PING_CHECK", "PING_CHECK"))
        self.IP_address.setPlaceholderText(_translate("PING_CHECK", "ex:192.168.1.1"))
        self.label_2.setText(_translate("PING_CHECK", "Enter IP ADDRESS"))
        self.PING.setText(_translate("PING_CHECK", "PING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PING_CHECK = QtWidgets.QMainWindow()
    ui = Ui_PING_CHECK()
    ui.setupUi(PING_CHECK)
    PING_CHECK.show()
    sys.exit(app.exec_())
