# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Device_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NOMUS(object):
    def setupUi(self, NOMUS):
        NOMUS.setObjectName("NOMUS")
        NOMUS.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(NOMUS)
        self.centralwidget.setObjectName("centralwidget")
        self.Username = QtWidgets.QLineEdit(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(250, 150, 131, 31))
        self.Username.setObjectName("Username")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 160, 81, 17))
        self.label.setObjectName("label")
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(250, 190, 131, 31))
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.PASSWORD = QtWidgets.QLabel(self.centralwidget)
        self.PASSWORD.setGeometry(QtCore.QRect(160, 200, 81, 17))
        self.PASSWORD.setObjectName("PASSWORD")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 234, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 240, 67, 17))
        self.label_2.setObjectName("label_2")
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(280, 340, 89, 25))
        self.Run.setObjectName("Run")
        self.Select_ini_file = QtWidgets.QLabel(self.centralwidget)
        self.Select_ini_file.setGeometry(QtCore.QRect(90, 310, 101, 21))
        self.Select_ini_file.setObjectName("Select_ini_file")
        self.select_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.select_dropdown.setGeometry(QtCore.QRect(210, 310, 391, 25))
        self.select_dropdown.setObjectName("select_dropdown")
        self.edit_ini_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.edit_ini_checkbox.setGeometry(QtCore.QRect(240, 280, 161, 23))
        self.edit_ini_checkbox.setObjectName("edit_ini_checkbox")
        NOMUS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NOMUS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        NOMUS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NOMUS)
        self.statusbar.setObjectName("statusbar")
        NOMUS.setStatusBar(self.statusbar)

        self.retranslateUi(NOMUS)
        QtCore.QMetaObject.connectSlotsByName(NOMUS)

    def retranslateUi(self, NOMUS):
        _translate = QtCore.QCoreApplication.translate
        NOMUS.setWindowTitle(_translate("NOMUS", "NOMUS COMM SYSTEMS"))
        self.label.setText(_translate("NOMUS", "USERNAME"))
        self.PASSWORD.setText(_translate("NOMUS", "PASSWORD"))
        self.label_2.setText(_translate("NOMUS", "Device IP"))
        self.Run.setText(_translate("NOMUS", "run_tests"))
        self.Select_ini_file.setText(_translate("NOMUS", "INI_FILE_EDIT"))
        self.edit_ini_checkbox.setText(_translate("NOMUS", "Edit INI File"))
