# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/Desktop/QT/FUNCTIONALITY_TOOL/ui/dummy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test_data_widget(object):
    def setupUi(self, test_data_widget):
        test_data_widget.setObjectName("test_data_widget")
        test_data_widget.resize(640, 480)
        self.test_data_wid = QtWidgets.QWidget(test_data_widget)
        self.test_data_wid.setGeometry(QtCore.QRect(120, 50, 291, 321))
        self.test_data_wid.setObjectName("test_data_wid")
        self.lineEdit = QtWidgets.QLineEdit(self.test_data_wid)
        self.lineEdit.setGeometry(QtCore.QRect(80, 140, 113, 25))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(test_data_widget)
        QtCore.QMetaObject.connectSlotsByName(test_data_widget)

    def retranslateUi(self, test_data_widget):
        _translate = QtCore.QCoreApplication.translate
        test_data_widget.setWindowTitle(_translate("test_data_widget", "Form"))
        self.lineEdit.setText(_translate("test_data_widget", "fdghfgjhfgfgfgfgj"))
