# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_window(object):
    def setupUi(self, log_window):
        log_window.setObjectName("log_window")
        log_window.resize(798, 561)
        self.label = QtWidgets.QLabel(log_window)
        self.label.setGeometry(QtCore.QRect(370, 10, 191, 17))
        self.label.setObjectName("label")
        self.logs_display = QtWidgets.QTableWidget(log_window)
        self.logs_display.setGeometry(QtCore.QRect(80, 40, 601, 371))
        self.logs_display.setObjectName("logs_display")
        self.logs_display.setColumnCount(0)
        self.logs_display.setRowCount(0)
        self.refresh_btn = QtWidgets.QPushButton(log_window)
        self.refresh_btn.setGeometry(QtCore.QRect(240, 420, 89, 25))
        self.refresh_btn.setObjectName("refresh_btn")
        self.export_btn = QtWidgets.QPushButton(log_window)
        self.export_btn.setGeometry(QtCore.QRect(420, 420, 89, 25))
        self.export_btn.setObjectName("export_btn")

        self.retranslateUi(log_window)
        QtCore.QMetaObject.connectSlotsByName(log_window)

    def retranslateUi(self, log_window):
        _translate = QtCore.QCoreApplication.translate
        log_window.setWindowTitle(_translate("log_window", "log"))
        self.label.setText(_translate("log_window", "Logs"))
        self.refresh_btn.setText(_translate("log_window", "Refresh"))
        self.export_btn.setText(_translate("log_window", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    log_window = QtWidgets.QWidget()
    ui = Ui_log_window()
    ui.setupUi(log_window)
    log_window.show()
    sys.exit(app.exec_())
