# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_1(object):
    def setupUi(self, page_1):
        page_1.setObjectName("page_1")
        page_1.resize(640, 480)
        self.pushButton = QtWidgets.QPushButton(page_1)
        self.pushButton.setGeometry(QtCore.QRect(0, 50, 121, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(page_1)
        QtCore.QMetaObject.connectSlotsByName(page_1)

    def retranslateUi(self, page_1):
        _translate = QtCore.QCoreApplication.translate
        page_1.setWindowTitle(_translate("page_1", "page_1"))
        self.pushButton.setText(_translate("page_1", "open_page_2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_1 = QtWidgets.QWidget()
    ui = Ui_page_1()
    ui.setupUi(page_1)
    page_1.show()
    sys.exit(app.exec_())
