# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_2(object):
    def setupUi(self, page_2):
        page_2.setObjectName("page_2")
        page_2.resize(640, 480)
        self.label = QtWidgets.QLabel(page_2)
        self.label.setGeometry(QtCore.QRect(220, 170, 161, 121))
        self.label.setObjectName("label")

        self.retranslateUi(page_2)
        QtCore.QMetaObject.connectSlotsByName(page_2)

    def retranslateUi(self, page_2):
        _translate = QtCore.QCoreApplication.translate
        page_2.setWindowTitle(_translate("page_2", "page_2"))
        self.label.setText(_translate("page_2", "WEL COME TO PAGE 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_2 = QtWidgets.QWidget()
    ui = Ui_page_2()
    ui.setupUi(page_2)
    page_2.show()
    sys.exit(app.exec_())
